Makefile, README.md
I made the Makefile to automatically converting xml to txt.
It will be easy to generate xml and pdf files, if we have md file format later.
=> For generating draft file in txt format from xml

draft-ietf-teep-protocol.xml
**IMPORTANT: pull request #3 is a strict super set of this pull request.**
=> Fix unterminated XML tag

draft-ietf-teep-protocol.md
Thank you for accpepting me as the co-author.
Please apply.
=> Adding my co-author affiliation details

draft-ietf-teep-protocol.md
=> Add discussion of confidentiality of EATs

draft-ietf-teep-protocol.md
oscp is changed to ocsp. ocsp_data is changed to ocsp-data for consistency.
=> Fix ocsp references and typo

draft-ietf-teep-protocol.md
Addresses issue #48 and part of issue #13
Key requirement is to allow for a format other than EAT to be used
as motivated by those issues, while still being optimized for EATs.
=> Add attestation agility as required by sec 8 of arch draft

draft-ietf-teep-protocol.md
=> Explain use of TEEP protocol version parameter

draft-ietf-teep-protocol.md
The bullet at line 806 and the next bullet following it had exactly the same label.
I have attempted to change the first one which looks like the wrong label.
=> Fix duplicate label

draft-ietf-teep-protocol.md
=> Add requested-ta-list and unneeded-ta-list

draft-ietf-teep-protocol.md
=> SUIT manifest processing errors

draft-ietf-teep-protocol.md
This is for https://github.com/ietf-teep/teep-protocol/issues/62
=> List all supported cipher suites as an array

draft-ietf-teep-protocol.md
left over of removing ERR_RESOURCE_FULL = 11
=> Reflect the change ERR_MANIFEST_PROCESSING_FAILED = 17

draft-ietf-teep-protocol.md
Also fix some other typos where the text and the CDDL didn't match
This is the PR we discussed in principle in the editors meeting, now created.  Would like to merge before submission.
=> Rename Install/Delete messages

draft-ietf-teep-protocol.md
=> Specify how TA_ID is used

draft-ietf-teep-protocol.md
Found some mistakes in binary representation in examples during implementation for hackathon
=> Fix: some wrong conversion to hex values

draft-ietf-teep-protocol.md
Per IETF 109 meeting
Addresses issue #70
=> Use SUIT_Component_Identifier as the TAID

draft-ietf-teep-protocol.md
There may be more drastic changes based on WG discussion at IETF 109.
We need to decide whether to keep token in all messages or remove it
from some messages.
Addresses issues #78
Also relates to issues #40 #71 #83
=> Token changes

draft-ietf-teep-protocol.md
Addresses issue #81
Also adds a TODO where issue #43 resolution would affect text
(possibly among other places)
=> Add beginnings of behavioral specification

draft-ietf-teep-protocol.md
Fixes #111 
Corresponding change to transport spec is https://github.com/ietf-teep/otrp-over-http/pull/33
=> Handle multiple TAMs with RequestPolicyCheck API

draft-ietf-teep-protocol.md
=> Explain why multiple signature mechanisms exist

draft-ietf-teep-protocol.md
Addresses #67
Uses the claims mentioned in PR #113
=> Add sample EAT

draft-ietf-teep-protocol.md
=> Fix compilation error

draft-ietf-teep-protocol.md
This PR is to solve https://github.com/ietf-teep/teep-protocol/issues/130
=> [hackathon] Change the size of challenge to 512 bytes to support Intel SGX attestation

draft-ietf-teep-protocol.md
To match https://github.com/ietf-teep/architecture/pull/219
Addresses issue #125 
=> Update TA Signer and Developer to be TC

draft-ietf-teep-protocol.md
Addresses last point in #132 as discussed at IETF 110
=> Add text around future ciphersuites without confidentiality

draft-ietf-teep-protocol.md
Per discussion at IETF 110.  See slide 18 of
https://datatracker.ietf.org/meeting/110/materials/slides-110-teep-teep-protocol-00
and the associated minutes.
Addresses #127
=> Clarify that token and challenge should not both be present

draft-ietf-teep-protocol.md
Addresses #43 per discussion at IETF 109
=> Clarify that Success/Error may take some time due to dependency resolution

draft-ietf-teep-protocol.md
Addresses #131 per discussion at IETF 110
=> Freshness mechanism negotiation

draft-ietf-teep-protocol.md
The message, supported-freshness-mechanisms, was added from
draft-06 and reflect the change to CDDL format.
Signed-off-by: Akira Tsukamoto <akira.tsukamoto@aist.go.jp>
=> Update CDDL format for supported-freshness-mechanisms

draft-ietf-teep-protocol.md
This updates the text to match section 8 as discussed at IETF 111.
Addresses #144
=> Use of challenge when freshness mechanism is not nonce

draft-ietf-teep-protocol.md
The install example should match Brendan's IETF 111 [slides](https://datatracker.ietf.org/meeting/111/materials/slides-111-teep-sessa-teep-manifest-00)
The delete example was from Brendan's email.
Addresses issue #41
=> Add SUIT manifest examples

draft-ietf-teep-protocol.md
=> Require ext-list in response when extensions but is set

draft-ietf-teep-protocol.md
Per discussion at IETF 112
Fixes #17
Fixes #40
=> Allow unsolicited QueryResponse

draft-ietf-teep-protocol.md
This PR is adding descriptions and formats of three types of suit manifests in the Update massages for explaining the implementation details of suit in teep message.
It is for these issues.
https://github.com/ietf-teep/teep-protocol/issues/158
https://github.com/ietf-teep/teep-protocol/issues/41
=> Adding three examples of suit manifests

draft-ietf-teep-protocol.md
And wordsmithing in various places
=> Replace tc.org with example.org

draft-ietf-teep-protocol.md
Per IETF 112 discussion.
Potentially fixes #165 
=> Update EAT claims

draft-ietf-teep-protocol.md
from
https://datatracker.ietf.org/meeting/111/materials/slides-111-teep-sessa-teep-suit-report-00
Fixes #170
=> Add SUIT Report examples

draft-ietf-teep-protocol.md
Fixing minor typo.
Signed-off-by: Akira Tsukamoto <akira.tsukamoto@aist.go.jp>
=> Fixing minor typo.

README.md
Almost perfect instructions for testing the markdown file by converting to xml and txt
with both minimal fedora and ubuntu image.
=> Improving README further for converting draft from markdown file

draft-ietf-teep-protocol.md
This PR is to improve ciphersuites with using cose tags discussed at https://github.com/ietf-teep/teep-protocol/issues/183
=> Use cose tags in ciphersuites

draft-ietf-teep-protocol.cddl
This PR fixes cddl syntax errors reported by @PenglinYang at https://github.com/ietf-teep/teep-protocol/issues/198
=> Fix cddl syntax errors

draft-ietf-teep-protocol.md
=> Specify default evidence format

draft-ietf-teep-protocol.md
This PR is preparation for the https://github.com/ietf-teep/teep-protocol/issues/208
The link to the draft:
https://www.ietf.org/archive/id/draft-ietf-suit-report-01.html
=> Fix definition of SUIT_Report to match with the draft

draft-ietf-teep-protocol.md
=> Add selected-cipher-suite default behavior

draft-ietf-teep-protocol.cddl, draft-ietf-teep-protocol.md
=> Make supported-ciphersuites be mandatory in QueryRequest

draft-ietf-teep-protocol.md
=> How to distinguish Evidence from Attestation Result in QueryResponse

draft-ietf-teep-protocol.md
=> Allow Attestation Result in Update message

draft-ietf-teep-protocol.cddl, draft-ietf-teep-protocol.md
Also make freshness-mechanism be a socket in the body not just the appendix
Addresses #226
=> Move freshness mechanism registry to rats interaction model draft

draft-ietf-teep-protocol.cddl, draft-ietf-teep-protocol.md
=> Hackathon 114: Cipher suite should be two words according to various dictionaries

draft-ietf-teep-protocol.md
=> Add informative reference to concise-ta-stores

draft-ietf-teep-protocol.md
=> Send Error in response to invalid TEEP message

draft-ietf-teep-protocol.md
=> Use "scenarios" instead of "examples" for Update use cases

draft-ietf-teep-protocol.md
Addresses #240
The preceding paragraph talks about version 0 so it should be clear enough in context given that.
=> State default profile in a way that implies it is version specific

draft-ietf-teep-protocol.md
=> Add more text about duration of freshness

draft-ietf-teep-protocol.md
=> Explain randomness of tokens better

draft-ietf-teep-protocol.md
=> EAT alternatives

draft-ietf-teep-protocol.md
=> `profile` -> `eat_profile`

draft-ietf-teep-protocol.md
=> Add Privacy Considerations

draft-ietf-teep-protocol.md
Addresses #234 #251
This PR, as suggested by @ko-isobe , is an alternative to PR #253.
=> Use COSE_Sign with QueryRequest

draft-ietf-teep-protocol.md
Addresses #269
Is this the approach we want for 269?
@kentakayama any comment?
=> State that CDDL appendix is not normative

cbor/Makefile, cddl/Makefile
Align the dependency rules, and fix cbor Makefile target.
=> Makefile update

draft-ietf-teep-protocol.cddl, draft-ietf-teep-protocol.md
This fixes various contradictions where the CDDL snippets in the body and the complete CDDL at the end did not match.
Addresses #262
=> Align CDDL between appendix and body

draft-ietf-teep-protocol.md
=> Remove unused references

cbor/update.diag.txt
This is an attempt to use the SUIT_Envelope
=> Update message with SUIT_Envelope

draft-ietf-teep-protocol.md
This PR is for https://github.com/ietf-teep/teep-protocol/issues/273.
=> Removing one last CBOR tag

draft-ietf-teep-protocol.cddl, draft-ietf-teep-protocol.md
=> Use SUIT Manifest Component ID in unneeded-manifest-list

cbor/suit_integrated.diag.txt, cbor/suit_personalization.diag.txt, cbor/suit_unlink.diag.txt, cbor/suit_uri.diag.txt
Shorten comments in SUIT manifests.
Will not affect on cbor binary and cddl validation.
Thank you @mcd500 for your review and advice!
=> [5/5] Add TEEP and SUIT CDDL validation

draft-ietf-teep-protocol.md
Per discussion at IETF 115
Addresses #289
=> Relationship between TEEP EAT profile and AR4SI

draft-ietf-teep-protocol.md
=> update media type

draft-ietf-teep-protocol.md
Also update labels to match the latest EAT spec
Addresses #285
=> EAT manifests claim in TEEP profile

draft-ietf-teep-protocol.md
Only one more fix for reference error.
=> Fixing one more reference

draft-ietf-teep-protocol.md
=> Replace HPKE with ECDH

draft-ietf-teep-protocol.md
=> Use token for Passport model attestation nonce

draft-ietf-teep-protocol.cddl
The cddl file was out of sync after the chages was made to md file last time.
=> Update the cddl reflecting the md changes

draft-ietf-teep-protocol.cddl, draft-ietf-teep-protocol.md
Adding the err-code in cdd section in md.
It was forgotten after adding the err-code in the Label table.
=> Fix err code

draft-ietf-teep-protocol.md
Akira started to work at ALAXALA Networks Corporation from June 12 Monday.
=> Updating Akira's origination

draft-ietf-teep-protocol.md
=> Allow Update with error info in response to a QueryResponse

draft-ietf-teep-protocol.md
Also fix references to TEEP architecture RFC
=> Add paragraph about replay protection

draft-ietf-teep-protocol.md
See https://github.com/ietf-rats-wg/eat/pull/420
Addresses #371
=> Use URN for the profile id, as the EAT spec now does

draft-ietf-teep-protocol.md
Addresses #365 by simply removing the misleading sentence
=> Remove misleading sentence

draft-ietf-teep-protocol.md
=> Confidentiality of EATs and SUIT Reports from TAM

draft-ietf-teep-protocol.md
=> Remove .suit suffix from SUIT manifest filenames

draft-ietf-teep-protocol.md
Replaces https://github.com/ietf-teep/teep-protocol/pull/366
=> Editorial Fixes

draft-ietf-teep-protocol.cddl, draft-ietf-teep-protocol.md
Addresses #356
@kentakayama please review and advise if this is not correct.
=> Update suit cose profiles

draft-ietf-teep-protocol.cddl, draft-ietf-teep-protocol.md
=> Explain how TEEP Agent should handle SUIT Reports in QueryRequest

draft-ietf-teep-protocol.md
This PR is suupliment for the https://github.com/ietf-teep/teep-protocol/pull/382
=> Adding explantion of ERR_UNSUPPORTED_SUIT_REPORT
