ietf-teep/teep-protocol

draft-ietf-teep-protocol.xml

**Merging this PR automatically merges #8**. The only reason I separated #8 is because this is a different issue.
I examined CDDL definitions of the TEEP protocol and found some errors (I think).
My fix is checked on the CDDL tool mentioned in RFC 8610 (CDDL) as “A rough CDDL tool”.
If I got it wrong, sorry and let me know.
`data_items`
-------------
`data_items` type (used in `QueryRequest`) is intended to be an integer type which indicates what information the TAM requests from the TEEP Agent. It is like `enum` in C-based languages.
However, the original CDDL definition declares that, `data_items` is a group of sequence 1, 2, 3 and 4. As a consequence, `REQUEST` field conforms to the CDDL definition only when it consists of repetition of 1, 2, 3 and 4 (e.g. `[1,2,3,4]`, …

Fix CDDL definitions

---

draft-ietf-teep-protocol.xml

I know, this is not relevant to the TEEP protocol itself. But it changes contributor names.
1.  “Isobe Kohei” and “Kohei Isobe” seems to be the same person (_missing_ contributor?)  
I propose to keep the name represented by western “given name, family name” order (“Kohei Isobe”) and remove the another (“Isobe Kohei”).  I recommend to check whether “missing” contributor exists.  
**Edit:** It's likely that Mr. Kuniyasu Suzaki from TRASIO/AIST is the _missing_ contributor considering SIoT and IETF 106 hackathon participants.
2.  “Tsukasa Oi” (who made this proposal) prefers this passport name  
I used "Ooi" until early 2011 because it's more faithful to original Japanese representation (three mora "o-o-i", two syllables "oo-i") but this romanization did not match to my passport which …

Possible fix (and change) for contributor names

---

.gitignore
README.md

The packages installed by apt was old and the kdrfc did not have -3 option.

Fix the right version of tools to install

---

draft-ietf-teep-protocol.md

Sections 4.6 and 4.7 say success is 5 and error is 6.
The CDDL has them backwards and says error is 5 and success is 6.

Fix CDDL message type numbers to match sections 4.6 and 4.7

---

draft-ietf-teep-protocol.md

This is for https://github.com/ietf-teep/teep-protocol/issues/54.
Revised to use only supported-cipher-suites.
Both supported-cipher-suites and cipher-suites were used in the draft but only cipher-suites had a map key.
Without the map key, it is not able to create the cbor binary.
Considering the usage of the cipher-suites, replacing the cipher-suites with supported-cipher-suites looks fine.

The cipher-suites was undefined, use only supported-cipher-suites

---

draft-ietf-teep-protocol.md

These changes are for fixing errors when generating xml and txt files from md.
Fixes following error messages:
```
xml2rfc draft-ietf-teep-protocol-latest.xml
Error: Unable to validate the XML document: draft-ietf-teep-protocol-latest.xml
<string>: Line 479: IDREF attribute target references an unknown ID "RFC4122"
<string>: Line 776: IDREF attribute target references an unknown ID "ciphersuit-registry"
Makefile:4: recipe for target 'draft-ietf-teep-protocol-latest.txt' failed
make: *** [draft-ietf-teep-protocol-latest.txt] Error 1
```

Fix errors when generating xml txt from md

---

draft-ietf-teep-protocol.md

While attempt prototyping, found that mandatory member in teep-error was written after options in the draft.

Fix order, mandatory member in front of options for CBOR parsing

---

draft-ietf-teep-protocol.md

PR #60 removed ERR_MANIFEST_PROCESSING_FAILED and other error codes for when manifest processing failed.  But the suit-reports parameter
is optional and regardless of whether it is present, one needs to
have an error code in the Error response.
This PR restores the ERR_MANIFEST_PROCESSING_FAILED error code, used any time there are any failures processing the SUIT manifest.
It also removes other error codes that should be covered by SUIT reports
since they occur when trying to apply a SUIT manifest.

Update manifest processing error codes

---

draft-ietf-teep-protocol.md

Some places had requested-ta-list and other places had
requested-tc-list.  They were originally fixed in PR #56 but
got broken due to bad merge conflict resolutions when PR #53 was
rebased.

Fix contradictory terms

---

Makefile
draft-ietf-teep-protocol.md

Fixes errors when generating xml and txt from md by my examples commit in the past.
The error message:
xml2rfc draft-ietf-teep-protocol-latest.xml
/teep-protocol/draft-ietf-teep-protocol-latest.xml(1472): Error: Did not expect a numbered section under an unnumbered parent section (seen on line 1470)
/teep-protocol/draft-ietf-teep-protocol-latest.xml(1489): Error: Did not expect a numbered section under an unnumbered parent section (seen on line 1470)
/teep-protocol/draft-ietf-teep-protocol-latest.xml(1533): Error: Did not expect a numbered section under an unnumbered parent section (seen on line 1470)
/teep-protocol/draft-ietf-teep-protocol-latest.xml(1577): Error: Did not expect a numbered section under an unnumbered parent section (seen on line 1470) …

Fix: error generating xml and txt by can not use numbering index after turning it off once

---

draft-ietf-teep-protocol.md

For consistency with the evidence being mandatory if attestation bit is
set
Addresses #80

[Hackathon] Make tc-list mandatory if trusted-components bit is set

---

draft-ietf-teep-protocol.md

Per IETF 109 meeting discussion, make both suites mandatory to implement
on TAM and allow Agent to chose any.
Also clarify that a ciphersuite is not a bitmap, it's an array element.
Addresses issues #72 and #73

Ciphersuite clarifications

---

draft-ietf-teep-protocol.md

This PR reflects the binary representation of tc-list in query-response after it was changed from using uuid
@dthaler Please review.

Fix binary repression of tc-list after it changed from using uuid

---

draft-ietf-teep-protocol.md

These series of patches are typos found when we were proceeding the prototyping after ietf 109.
@dthaler Appreciate for your review.

Minior typo in hex

---

draft-ietf-teep-protocol.md

After we change the token entry in teep message from mandatory entry to option entry, the numbers of entry in array have decreased.
This PR reflects the changes in binary representation.
@dthaler  Do you mind reviewing this PR?

Fix array number in hex

---

draft-ietf-teep-protocol.md

This fixes the error when generating xml and txt file from md file.
This is the error message if it has the year 2020.
```
$ make
kramdown-rfc2629 draft-ietf-teep-protocol.md > draft-ietf-teep-protocol-latest.xml
---
- 'No link definition for link ID ''[tbd: this rfc]'' found on line 1000'
- 'No link definition for link ID ''tbd: this rfc'' found on line 1000'
- 'No link definition for link ID ''[tbd: this rfc]'' found on line 1002'
- 'No link definition for link ID ''tbd: this rfc'' found on line 1002'
- No link definition for link ID ' 0x0102030405060708090a0b0c0d0e0f ' found on line
1304
- No link definition for link ID ' 0x1102030405060708090a0b0c0d0e0f ' found on line
1305
Incorrect section nesting: Need to start with 1
xml2rfc draft-ietf-teep-protocol-latest.xml …
```

Fix error when generating xml from md from mismatch year

---

draft-ietf-teep-protocol.md

While I was working on https://github.com/ietf-teep/teep-protocol/issues/99 for adding .size for entries, I realized that err-code listing was missing in the cddl section.
This PR adds err-codes in the cddl description.
@dthaler please review

Add err code

---

draft-ietf-teep-protocol.md

For each required item mentioned in the TEEP architecture add a reference to a RATS claim that can meet that requirement.
Addresses #49

Add references to RATS claims

---

draft-ietf-teep-protocol.md

This is related to #83 and #43 but still leaves open the question of whether we can remove the token field from some or all messages.

Add reference to suit-report-nonce

---

draft-ietf-teep-protocol.md

The SUIT manifest section 8.7.8 now includes suit-directive-garbage-collect which allows deletion to be done by SUIT manifests.

Remove unneeded-tc-list from Update message

---

draft-ietf-teep-protocol.md

Differences just meant for diagnosis only should use err-msg instead of error codes.
Fixes #51

Use error codes to denote expected TAM behavioral differences

---

draft-ietf-teep-protocol.md

Was true when the doc had TEEP-P but not when we dropped the -P

Remove obsolete paragraph from abstract

---

draft-ietf-teep-protocol.md

There was one place it was still using TA instead of TC.

Fix remaining TA after changing from TA to TC

---

draft-ietf-teep-protocol.md

Minor fixes found during ietf110 hackathon.
Unifying the upper/lower cases in the examples, and remove the left over unneeded-tc-list.

[hackathon] Unify the upper/lower cases and remove the left over unneeded-tc-list

---

draft-ietf-teep-protocol.md

Addresses issue #132 except that it does not yet address the comment "In Section 9, please say whether future registrations will allow integrity-without-confidentiality ciphersuites. Let's settle this now instead of dumping on the IANA Expert."
Will cover that in a separate PR after discussion in TEEP meeting.
All the others are straightforward.

Address Russ's comments on draft -05

---

draft-ietf-teep-protocol.md

Section 3 already had text that explicitly allowed Error in response to QueryRequest but sections 6.1 and 6.2 were missing equivalent text.  This PR corrects that oversight.
Addresses #129 per discussion at IETF 110

Allow Error in response to QueryRequest

---

draft-ietf-teep-protocol.md

Found during hackathon while implementing freshness mechanism negotiation.
Also rename `ERR_UNSUPPORTED_CRYPTO_ALG` to `ERR_UNSUPPORTED_CIPHER_SUITES` for consistency (no impact on actual wire protocol).
Addresses #143 

Add ERR_UNSUPPORTED_FRESHNESS_MECHANISMS error code

---

draft-ietf-teep-protocol.md

Per IETF 111 discussion (https://notes.ietf.org/notes-ietf-111-teep),
this change is made to just use COSE_Sign1 directly without a TEEP tag.
Addresses #147

Remove TEEP CBOR tag

---

draft-ietf-teep-protocol.md

Per IETF 111 [discussion](https://notes.ietf.org/notes-ietf-111-teep).  Just use SUIT reports to discover lack of such support when an error occurs.
Addresses issue #145

Remove suit-commands bit

---

draft-ietf-teep-protocol.md

This PR fixes the explanation of QueryResponse requested-tc-list.
I think it is derived from REE's RequestTA API call.

Fixing typo in QueryResponse requested-tc-list

---

draft-ietf-teep-protocol.md

Related to #167.
This PR contains following modify about ciphersuite
* Define `suite` structure. 'suite' is an array and has three algorithm identifiers correspond with three mechanisms; sign, encrypt and MAC.
* Remove the IANA request for TEEP ciphersuites. Instead of this, declare that algorithm identifiers depends on COSE Algorithm registry.
* Define MTI algorithms and other available sign algorithms from former ciphersuites and discussion.   Encrypt and MAC available algorithms are TBD due to no discussion about this currently.
* Minor fix to build the draft. (update new year, insert 'no' numbered)

Ciphersuite

---

draft-ietf-teep-protocol.md

This PR fixes the CDDL part for future version:
- replace `suite` with `ciphersuite`
- remove unnecessary comma and space

[hackathon] Fix ciphersuite

---

draft-ietf-teep-protocol.md

The hwmodel claim is newly added to EAT as shown in https://www.ietf.org/rfcdiff?url2=draft-ietf-rats-eat-12.txt
This PR proposes to use it to meet the "class of device" requirement in the teep arch doc.   If we later find it is not sufficient, we can always add an extension once it is shown to be needed.

Use hwmodel claim added in EAT draft-12

---

draft-ietf-teep-protocol.md

One line changes to fix error from pandoc tools when generating pdf from md file.
The following command will work now.
```
pandoc draft-ietf-teep-protocol.md -o draft-ietf-teep-protocol-latest.pdf
```

Avoid error by pandoc when converting to pdf from md

---

draft-ietf-teep-protocol.md

Previously was only in Success and Error message.
This allows system information such as TEE type to be used by the TAM when evidence is not requested in the QueryRequest, and to avoid relying on a Verifier to copy the relevant information into Attestation Results.
See issue #189 

Add SUIT reports to QueryResponse message

---

draft-ietf-teep-protocol.md

Fixing I-D.moran-* to I-D.ietf-* since they fails when generating xml from md file
while fetching them from rfc-editor.org.

Fix fetching I-D.ietf- fails when generating xml

---

draft-ietf-teep-protocol.md

The CDDL of SUIT_Envelope is defined in I-D.ietf-suit-manifest precisely, which conflicts here.

Removing SUIT_Envelope in TEEP Protocol CDDL

---

draft-ietf-teep-protocol.md

Removing mentioning on IANA registration in data-item-requested,
since IANA does not define such registry.
This PR is for the issue https://github.com/ietf-teep/teep-protocol/issues/188.

Remove mentioning on IANA registration in data-item-requested

---

draft-ietf-teep-protocol.md

Clarify that the Passport model is not illegal in TEEP even if it's not typical.
Fixes #185

Clarify use of Attestation Results

---

draft-ietf-teep-protocol.cddl

This fixes syntax error introduced by https://github.com/ietf-teep/teep-protocol/pull/194

Fix assignments were missing in cose-algs

---

draft-ietf-teep-protocol.md

The label in the query-request CDDL is versions not version

Fix versions in label table

---

draft-ietf-teep-protocol.md

Also include the profile URI with the media type per draft-lundblade-rats-eat-media-type.
This also has the effect of addressing an ART area issue where https://trac.ietf.org/trac/art/wiki/TypicalARTAreaIssues says:
> If your spec has a protocol element that is defined to contain a media type, make sure you specify if MIME-related parameters are allowed (e.g. 'text/plain' versus 'text/plain;charset=UTF-8').
Fixes #217 #214

Use media type as defined in draft-lundblade-rats-eat-media-type

---

draft-ietf-teep-protocol.md

Just fixes several bugs in CBOR binaries and its diagnostics notations.

[hackathon] fix TEEP Protocol message examples

---

draft-ietf-teep-protocol.cddl
draft-ietf-teep-protocol.md

* Change CDDL ciphersuite to $ciphersuite to be explicit that it supports extensibility
* Remove MAC and Encrypt algorithms and leave them to extensions
* Remove COSE_Sign_Tagged and leave it to extensions
* Fix contradiction between CDDL in body vs appendix (issue #208)
* Specify the order of operations within a ciphersuite is meaningful
* Make it clear that Agent only needs to support cose-sign1
Addresses #220

Hackathon feedback around ciphersuites

---

draft-ietf-teep-protocol.md

And remove mention of the not-fully-defined epoch ID mechanism, leaving it to an extension.
Addresses #235

Make Nonce mechanism MTI and others optional

---

draft-ietf-teep-protocol.cddl
draft-ietf-teep-protocol.md

It was originally removed in PR #118.
But issue #238 was then encountered during implementation. This RP restores the field in the hopes that either:
a) the SUIT manifest will allow unlink directions in an install manifest (option 2-2 in PR #169, and now tracked in https://github.com/bremoran/suit-multiple-trust-domains/issues/3), or 
b) a TEEP Agent can somehow figure out how to uninstall an installed component (option 2-1 in PR #169)

Add unneeded-tc-list back into Update message

---

Makefile
draft-ietf-teep-protocol.md

A number of small fixes:
* fix off-by-one in EAT `manifests` claim reference
* update CBOR and COSE references (7049 and 8152 have been obsoleted by 8949 and 9052 respectively)
* increase reference precision (including sections in the generated hyperlink)

a bunch of fixes around references

---

README.md

This is my found when I was trying cddl syntax check and Ken's PR.
There are two packages for kramdown-rfc2629 on ubuntu.
The ruby-kramdown-rfc2629 with apt and kramdown-rfc2629 with gem.
The ruby-kramdown-rfc2629 depends on old ruby 2.5 or older and do not work on ubuntu 20.04 or later which has ruby 2.7.
This PR fixes it by installing the kramdown-rfc2629 with gem which works on ruby 2.7 in ubuntu 20.04.
I was using ubuntu 18.04 when I wrote the initial instruction in the README.

Use newer kramdown-rfc2629 on ubuntu

---

draft-ietf-teep-protocol.md

The email address of aist.go.jp is not reachable now.
Akira was working at AIST until the end of December 2022.

Updagin Akira`s email address

---

draft-ietf-teep-protocol.md

We added text for the TEEP Agent in #252 but not for the TAM. The TAM cannot send an Error, but could try an Update.
Addresses the rest of #245

More fixes for unrecognized TEEP messages

---

draft-ietf-teep-protocol.md

This is updating the sentence to clarify the value to be in the eat_nonce when the QueryResponse contains challenge value. 
The format of EAT profile using a eat-claim-set was defined at the IETF 115, this PR updates according to it.

Use eat_nonce in EAT profile with challenge value from QueryResponse 

---

cddl/Makefile

Add depending SUIT Manifest extension `draft-suit-trust-domains.cddl` to CDDL validation for dependency-resolution, uninstall and unlink functionalities.

[0/5] Add TEEP and SUIT CDDL validation

---

cddl/Makefile
cddl/suit-envelope-shim.cddl

Create `check-draft-ietf-suit-manifest.cddl` to validate SUIT_Envelope (untagged).
Validates SUIT manifests with `check-draft-ietf-suit-manifest.cddl` and TEEP Protocol messages with `check-draft-ietf-teep-protocol.cddl` respectively.
Depends #299 , and [you can check the difference here](https://github.com/kentakayama/teep-protocol/compare/fix-cddl-v11-0-cat-cddl..fix-cddl-v11-1-Makefile).

[1/5] Add TEEP and SUIT CDDL validation

---

Makefile
README.md
cddl/Makefile
cddl/suit-envelope-shim.cddl

Update the sub-commands in Makefiles.
- `make validate` : validate both cbor and cddl
- `make validate-cddl` : validate only cddl
- `make validate-teep-cddl` : validate only TEEP Protocol CDDL with QueryRequest message.
Depends on #300, and [you can check the difference here](https://github.com/kentakayama/teep-protocol/compare/fix-cddl-v11-1-Makefile..fix-cddl-v11-2-Makefile-PHONY).

[2/5] Add TEEP and SUIT CDDL validation

---

cbor/Makefile

Refactored `cbor/Makefile`
- validate TEEP Protocol messages, then
- validate SUIT manifests

[3/5] Add TEEP and SUIT CDDL validation

---

draft-ietf-teep-protocol.cddl
draft-ietf-teep-protocol.md

Synchronizing the cddls in the body and appendix for maintenance.
Relate to #208 but not solve it (still manually checking).
- reflect "deleting EPOCH_ID" ( 8e1b8033043d5418abc1ac330be57fde3b3ce4eb ) to Appendix
- reflect "adding attestation-payload" ( f238d50e62e888bf7018fc67439ecf987807b018 ) to Appendix
- merge "cipher-suite comments" ( 3610445b44b3c8cd96020d55d42e7a7c29af360d and de1d2dda4711cfdf311c212c40dd534d29b46b5e )
I'm also working on solving #208 [here](https://github.com/kentakayama/teep-protocol/compare/master...always-synchronize-cddl-and-article-part?expand=1).

[Maintenance] Syncronize cddls in body and appendix

---

cbor/query_response.diag.txt
cbor/query_response.hex.txt

Solves #291 .
The TAM can get much information about TCs in the device such as the digest and version of the TC.

Add SUIT_Parameters to system-property-claims

---

cbor/query_request.diag.txt
cbor/query_request.hex.txt
cbor/query_response.diag.txt
cbor/query_response.hex.txt
draft-ietf-teep-protocol.cddl
draft-ietf-teep-protocol.md

This adds a mandatory field to the QueryRequest so is not backwards compatible.
Fixes #286

Add support for EAT and SUIT Report encryption

---

draft-ietf-teep-protocol.md

The date must be current year 2023 for xml2rfc tool to pass.

Fix errors found when running cddl tool and xml2rfc

---

draft-ietf-teep-protocol.md

draft-ietf-suit-firmware-encryption is the mechanism to encrypt payloads when using the SUIT manifest. I think draft-ietf-suit-firmware-encryption therefore needs to be normative if we want to encrypt TA binaries and personalization data. For the encryption of EATs and SUIT reports draft-ietf-suit-firmware-encryption is not used but instead the underlying primitives are used directly.

Making draft-ietf-suit-firmware-encryption normative

---

cbor/query_request.hex.txt
cddl/Makefile
draft-ietf-teep-protocol.cddl
draft-ietf-teep-protocol.md

Add reference to draft-moran-suit-mti
And more closely align with the SUIT profiles therein.
Address more of #286
Still may not be quite right since HPKE apparently uses an ephemeral public key, whereas this PR currently implies using the non-ephemeral public key of the TAM.
Compare https://github.com/bremoran/suit-mti/pull/2

Add reference to draft-moran-suit-mti

---

draft-ietf-teep-protocol.md

Uses cnf as suggested by Giri on the RATS mailing list.
This also fixes the issue that the EAT profile text said to use a "hash" without saying which algorithm to use.
Addresses #310

Add cnf to EAT profile to prevent impersonation attack

---

draft-ietf-teep-protocol.md

Fixes `uint .size 1` to `(0..23)`.
[RFC 8610](https://datatracker.ietf.org/doc/html/rfc8610#section-3.8.1) says below.
> The control is defined for text and byte strings, where it directly controls the number of bytes in the string.  It is also defined for unsigned integers (see below).
> ...
> When applied to an unsigned integer, the ".size" control restricts the range of that integer by giving a maximum number of bytes that should be needed in a computer representation of that unsigned integer.  In other words, "uint .size N" is equivalent to "0...BYTES_N", where BYTES_N == 256**N.
Our purpose to use `uint .size 1` is to limit the **encoded cbor binary length**, but the `.size` operator limits the represented value.
They are slightly different, for example, CDDL `uint .size 1` allows …

[hackathon] limiting encoded uint size with not `.size` but immediate

---

Makefile
draft-ietf-teep-protocol.cddl
draft-ietf-teep-protocol.md

Solves #208 .
`$ make ` extracts pieces of cddl from md file and concatenates them into cddl file.
Authors should modify not cddl file but md file, and commit both cddl and md files.
After you add new cddl piece in md file, you should also add the mark (like `cddl-query-request`) after the prefix `~~~~ cddl-foo` and insert sed command into Makefile around [here](https://github.com/kentakayama/teep-protocol/blob/extract-cddl/Makefile#L30).
- modified md file
- add `version`, `ext-info` and `data-item-requested`
- add `ERR_*` cddl
- add label cddl
- add `cddl-*` marks before each cddl piece
- updated cddl file
- now synchronized with cddl pieces in md file

[hackathon] Extract cddl from md file

---

draft-ietf-teep-protocol.md

Two other places in the document already said
"if a SUIT mechanism such as {{I-D.ietf-suit-firmware-encryption}} is used" where the "such as" was already informative.  This change updates the third place to use similar wording.
Addresses #327

Make suit-firmware-encryption be informative

---

cbor/Makefile
cbor/query_request.diag.txt
cbor/query_request.hex.txt
cbor/suit_personalization.diag.txt
cddl/Makefile
cddl/draft-ietf-suit-firmware-encryption.cddl
draft-ietf-teep-protocol.cddl

Fixing error in `make validate-cbor` and `make validate-cddl` (`make validate` in short).
- rm: suit_unlink manifest from `cbor/Makefile` and `cddl/Makefile` (Not necessary anymore.)
- nit: `suit_personalization.diag.txt`
- nit: `query_request.hex.txt`
- fix: the URL of SUIT MTI CDDL in `cddl/Makefile` (Because previous CDDL causes some error.)
- add: options label for `err-code` introduced in 076f3d3
- add: SUIT Encrypted Payload CDDL for suit_personalization (Manually added only necessary part to `cddl/draft-ietf-suit-firmware-encryption.cddl`)
Still waiting [a PR to be merged](https://github.com/suit-wg/suit-multiple-trust-domains/pull/10).
Or you can run CDDL validation with manually fix the generated CDDL files `cddl/check-draft-ietf-suit-manifest.cddl` and …

Fix v13 cbor and cddl

---

draft-ietf-teep-protocol.md

This PR fixes error found by idnits tool for I.D. submittion

Fix error of Normative reference to an Informational draft

---

README.md

Installing ruby and python only on the local user only is typically recommended,
instead of installing them system wide, for prevent version clash for other users who
prever different versions.

Fix sudo usage in README

---

draft-ietf-teep-protocol.md

This PR fixes only one warning.
== Outdated reference: draft-ietf-teep-architecture has been published as
RFC 9397
Others warnings are from the text appended after submitting the ID and
not able to fix on the original md file.
The entire log of idnits.
```
Miscellaneous warnings:
----------------------------------------------------------------------------
-- The document date (3 July 2023) is 21 days in the past.  Is this
intentional?
-- Found something which looks like a code comment -- if you have code
sections in the document, please surround them with '<CODE BEGINS>' and
'<CODE ENDS>' lines.
Checking references for intended status: Proposed Standard
----------------------------------------------------------------------------
(See RFCs 3967 and 4897 for information about using …
```

Fix warning idnits tools after TEEP Architecture became RFC

---

draft-ietf-teep-protocol.md

Per discussion in TEEP WG at IETF 117
Fixes #349

Add normative reference to draft-ietf-cose-key-thumbprint

---

cddl/Makefile

The xml tag wrapping CDDL has changed.
If you have local file of `rfc-9052-cose.xml` or `rfc-9052-cose.cddl`, please update them with `make -C cddl rfc-9052-cose.cddl -B`.

Respond to change RFC xml file

---

cbor/query_request.diag.txt
cbor/query_request.hex.txt
cbor/query_response.diag.txt
cbor/query_response.hex.txt
cddl/Makefile

@mcd500 
I've updated the QueryRequest example to list up suit-cose-profiles
- suit-sha256-es256-ecdh-a128ctr
- suit-sha256-eddsa-ecdh-a128ctr
- suit-sha256-es256-ecdh-a128gcm
- suit-sha256-eddsa-ecdh-chacha-poly

Fix suit-cose-profiles in examples

---

draft-ietf-teep-protocol.md

The two removed paragraphs (starting at "When a QueryRequest message is received...") duplicate other existing text a few paragraphs below, under the "Handling a QueryRequest Message" heading.
Also move Update message processing under its own subheading, for consistency.

Remove 2 redundant paragraphs

---

draft-ietf-teep-protocol.cddl
draft-ietf-teep-protocol.md

As discussed at Hackathon 118.
Since the selected suite is used to sign the QueryResponse, it can be determined from the envelope and need not be duplicated in the message itself.
For issue #379

Remove selected-teep-cipher-suite

---

cbor/query_request.diag.txt
cbor/query_request.hex.txt
draft-ietf-teep-protocol.md

The SUIT Profile suit-sha256-es256-ecdh-a128ctr has been updated from ECDH-ES+HKDF-256 (-25) to ECDH-ES+A128KW (-29).
This PR must be merged after the CDDL of [suit-mti](https://github.com/bremoran/suit-mti/blob/main/draft-ietf-suit-mti.cddl#L17-L20) is updated.
I'll quickly create an Issue and a PR to it.
After that, validate example binaries with `make validate -B` .

Reflect update on suit-sha256-es256-ecdh-a128ctr
